[#69] 푸시알림 위한 fcm 구현
mash-up-kr/gabbangzip-Android pull request #102
Opened 2024-07-11 07:43 UTC by SEO-J17

## Issue No
- close #69 

## Overview (Required)
- 백쪽에서 noti로만 준다 그래서 data는 빼놨습니다~
- 푸시는 첨해봐서 뭔가 달랐다면 코멘트 부탁 드립니다..

## Screenshot

https://github.com/mash-up-kr/gabbangzip-Android/assets/59912150/45dcfa1e-aa12-46ea-9198-b7bf74ae2c9a

2024-07-11 09:00 UTC, oreocube reviewed
고생했어~ 코멘트 확인 부탁~
그리고 우리 타겟 몇이지? 안드 13 알림 퍼미션 체크 안해도 린트 안뜨나?

2024-07-12 02:12 UTC, SEO-J17 commented
> 고생했어~ 코멘트 확인 부탁~ 그리고 우리 타겟 몇이지? 안드 13 알림 퍼미션 체크 안해도 린트 안뜨나?

린트같은거는 따로 안뜨긴 했어..! 그리고 알림 권한 체크하는 곳은 우리가 논의 된게 없어서 아직 어디에 넣을지를 모르기도 했고 api 들어올때 같이 할라고 하긴 했었어서..! 뭔가 지금 생각은 그냥 앱시작할떄 한번에 받아도 괜찮지 않을까..? 라는 생각..? 퍼미션 체크가 이거 말하는거 맞지..?

2024-07-12 02:12 UTC, SEO-J17 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            notificationManager.notify(NOTIFICATION_ID, notificationBuilder)
오... 몰랐습니다 그거는..? 랜덤 id로 주도록 하겠습니다..

2024-07-12 02:12 UTC, SEO-J17 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +                "Channel human readable title",
ㅋㅋㅋㅋ마자마자 나도 저게 고민이긴했었긴했어..! 우리 알람 형식이 다양하면 뭔가 다른 관리가 필요할거 같긴하더라고..? 훔.. 일단은 그런 "PIC 알람" 이런식으로 넣어놓을까?

2024-07-12 04:00 UTC, SEO-J17 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            notificationManager.notify(NOTIFICATION_ID, notificationBuilder)
적용 완!! [91bdc3e](https://github.com/mash-up-kr/gabbangzip-Android/pull/102/commits/91bdc3e25ab25de1158615ff98e7a93553562cc4)

2024-07-12 06:59 UTC, oreocube commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            notificationManager.notify(NOTIFICATION_ID, notificationBuilder)
호옹 코멘트는 불편하니까 여기다 이어서 달게 나는 회사에서 개발할때 notify할때 알림권한 체크하라고 린트가 떴었거든 그래서 13인데 권한 허용안한 상태에서도 문제가 없나 궁금해지넹

2024-07-12 07:03 UTC, oreocube commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +                "Channel human readable title",
그치그치 특정 카테고리 알람 거르는거 있으면 이름 지어주는게 좋지

2024-07-12 08:21 UTC, SEO-J17 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            notificationManager.notify(NOTIFICATION_ID, notificationBuilder)
아 런타임때 권한체크 말하는거 맞나..? 그거 라면 저기 코멘트 단거 처럼 앱 시작할때 한번에 받게하려고 하긴 했어..! 만약 권한 허용이 안되었으면 알림이 안오긴 하더라고..? 체크로직을 여기다가 넣어줘야 할까..? 나는 ui단에서 넣을라고 하긴 했었어서..!

2024-07-12 11:46 UTC, oreocube commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            notificationManager.notify(NOTIFICATION_ID, notificationBuilder)
런타임 권한 체크를 말한건 아니고 음.. 그냥 권한없는데 알림 notify 하면 권한없음 exception 이런건 안터지나보네 그럼 됐어~

2024-07-13 03:21 UTC, JeonK1 requested changes

2024-07-13 03:21 UTC, JeonK1 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/utils/NotificationUtil.kt
> +                .also { usedIdSet.add(it) }
엇 이거... 
(1) 만약에 random.nextInt() 로 나온 값이 usedIdSet 에 존재하는 값이면 NoSuchElementException 터질 것 같은데..? 괜찮은걸까..?!
(2) 지금은 usedIdSet 에 없을 때 random 으로 만든 값을 반환하는 동시에 usedIdSet 에 추가하는데, usedIdSet 에 있으면 어떻게 처리되는건지 처리가 없는 것 같은데 한번 확인해줄 수 있을까??

2024-07-13 03:24 UTC, JeonK1 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            notificationManager.notify(NOTIFICATION_ID, notificationBuilder)
13일 때 AndroidManifest.xml 에서 알림권한 관련하여 정의만 해두었으면, 런타임상에서 권한이 있는지 체크할 수 있지만 만약에 체크 안하면 어플리케이션에 대한 default 런타임권한 상태가 false 여서 아마 이 값으로 잡힐거라 문제 없을 것 같다는 생각이 들어!

2024-07-13 03:25 UTC, SEO-J17 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/service/PicMessagingService.kt
> +            val notificationBuilder = NotificationCompat.Builder(this, CHANEL_ID)
아 진짜 대박ㅋㅌㅋㅋㅌㅋㅋㅋㅋㅋㅋㅋㅋ 이번에도 나이스 캐치 좋았다~~~¿ 수정할게~~

2024-07-13 03:36 UTC, SEO-J17 commented on app/src/main/java/com/mashup/gabbangzip/sharedalbum/utils/NotificationUtil.kt
> +                .also { usedIdSet.add(it) }
(1) generateSequence에서 랜덤값을 계속 발생시켜주고 있는데 저게 의미가 int max 까지 난수를 계속 발생시켜주는거잖아?? 만약 set에 있다면 다시 난수를 발생시켜서 set에 없는 숫자가 나올때까지 반복을 하는 거였엉. 그래서 nosuch가 안나올거 같아...! 그 이후 set에 add 해서 숫자 중복을 방지 했어

(2) 위에서 말한대로 이미 위에서 중복이 안나올때까지 계속 반복을 하고 있어서 중복처리를 따로 안해줘도 될거같아..! 시퀀스라서 만약 add가 된다고 하더라도 set이라서 괜찮을거 같다는 생각이야..!

2024-07-15 07:09 UTC, JeonK1 approved these changes
나는 어푸~

2024-07-15 10:25 UTC, sooziini approved these changes
fcm 세팅하는 코드가 내가 생각했던 것보다 되게 간결한 것 같당 정우가 잘 작성해서 그런가? ㅡ?

2024-07-15 10:29 UTC, merged