[#15] Compose Navigation 기반 코드 작성
mash-up-kr/gabbangzip-Android pull request #16
Opened 2024-06-10 16:53 UTC by JeonK1

## Issue No
- close #15 

## Overview (Required)
- Compose Navigation 기반 코드 작성
- TopBar Composable 을 최대한 재사용할 수 있도록 별도 Composable 로 분리
- TopBar 유형별 State 정보를 담은 data class 생성
- MainViewModel 에서 TopBarState 관리

2024-06-15 09:10 UTC, sooziini approved these changes
고생하셨숩다~~~🤪 오빠오빠 ktlint 확인 바람.

2024-06-15 09:10 UTC, sooziini commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/main/MainViewModel.kt
> +    private val topBarStateStack: Stack<TopBarState> = Stack<TopBarState>().apply {
stack으로 관리 ..👏

2024-06-15 09:10 UTC, sooziini commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
지금 TopBar가 Main, Progress, Title 세 개가 있는데 밑에 두 개 케이스 등 더 추가되어야 할듯해!!
<img width="249" alt="image" src="https://github.com/mash-up-kr/gabbangzip-Android/assets/51108983/de135065-334c-4c43-9b57-2a19fa82ea7b">
<img width="280" alt="image" src="https://github.com/mash-up-kr/gabbangzip-Android/assets/51108983/cb3cc75c-7fb4-4063-9c06-5fb3439a3dd8">

그래서 나아는 개인적으로 특정한 topbar를 여러개 생성해두는 것보다는 TopBar 컴포저블 하나 만들어서 매개변수로 iconRes, text style, text align 등 커스텀하게 만들 수 있도록 넘겨주는 것은 어떨까 싶엉 디폴트 TobBar를 두고 커스텀 하고 싶으면 매개변수로 넘기는 느낌~

2024-06-15 09:11 UTC, sooziini commented
계원오빠가 작성한 navigation 설명 페이지: https://www.notion.so/Navigation-90aef7db22174deb84be76d793682b0e

2024-06-15 09:15 UTC, SEO-J17 reviewed
진짜 고생했어 계원아.. 역시 고수구나?? 

 코멘트 남긴것만 확인해줘..! 내가 잘 몰라서 궁금한 것만 코멘트 남기긴 했어..! 

확인하고 말해줘~~

2024-06-15 09:15 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/main/MainScreen.kt
> +                        },
뷰모델에서 스택으로 관리하는거 좋은거 같아! 근데 뭔가 update하는 함수 하나로도 할 수있을 거같아..!  

현재 route같은 값을 인자로 받고 뷰모델에서 when문으로 flow를 업데이트를 해주면 topbarState를 잘 관리할 수 있지 않을까? 라는 생각이 드네..?!

그렇게 되면 스택하고 pop해주는 함수도 굳이 작성안해도 될거 같아서..!

2024-06-15 09:15 UTC, SEO-J17 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
topbar 같은 공통 컴포넌트들은 preview 추가 해주기로 했는뒈... 일이 바빴구나?~ ㅎ.ㅎ 인정~

2024-06-15 09:59 UTC, oreocube requested changes
모디파이어 확인점~!

2024-06-15 09:59 UTC, oreocube commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +            modifier = modifier
혹시 여기는 인자로 받은 modifier를 사용하는 이유가 있을까? 인자로 받은 modifier는 최상위 컴포저블인 Row 에만 필요하지 않나 싶어서~ 
탑바에 적용하고 싶은 속성이 텍스트에도 적용될 수 있을 것 같아! 
근데 다른 TopBar 들도 그러넵..

2024-06-15 09:59 UTC, oreocube commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/main/MainScreen.kt
> +                        .wrapContentHeight(),
별건 아닌데 우리 modifier 첫번째 파라미터로 주기로 하지 않았었남?

2024-06-15 15:42 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/home/navigation/HomeNavigation.kt
> +    override val route: String = "home"
나 이거 개발하면서 한 곳으로 모아야한 패키지로 나누어야하나 고민이 되게 많았는데
써준 내용과 같이 한 곳에 모아두고 관리하는게 나중에 route 에 내용이 추가되고, 이를 관리하는 관점으로 보았을 때 훨씬 좋고 sealed class 로 묶어줄 수 있어서 더 좋을거같아

https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/bd94c023e7f3a555f412e46248cd4d0999bf1221
반영했어! 의견 고마워~

2024-06-15 15:43 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/TopBarState.kt
> +sealed class TopBarState {
마자마자 굳이 class 로 만들어줄 이유 없어보여
https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/295da154dd1385e15b0ec0a4f1959f2e9dec83ef 반영 완료!

2024-06-15 15:46 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/groupMake/navigation/GroupMakeNavigation.kt
> +}
음음 좋다고 생각해 반영 완료! https://github.com/mash-up-kr/gabbangzip-Android/commit/bd94c023e7f3a555f412e46248cd4d0999bf1221

2024-06-15 15:46 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/StartDestination.kt
이건 생각하지 못했었는데 이 방법 너무 좋은 것 같아
https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/16c7ae1def9c128cd363d607d11801e61d5bbf77
반영 완료!

2024-06-15 15:47 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/StartDestination.kt
> +    val ROUTE = LoginRoute.route
StartDestination object 를 아예 제거해서 이 문제도 자연스럽게 해결되었을 것 같아!

2024-06-15 15:48 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
세상에 그러네 개발하다보니 preview 를 까먹었었구나.. 이런 코멘트 너무너무 고마워
https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/24ee2b8786a2be213849aa7b31a5b73d1c2dd715 반영 완료!

2024-06-15 15:48 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/main/MainScreen.kt
> +                        .wrapContentHeight(),
아니?! 아주 중요한 사항이었어.
첫번째 파라미터로 주기로 했었는데 잘못들어가있었네
코멘트 고마워! 반영했어! https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/eee7026843ccaffd0588377d0851543e520a6f7a

2024-06-15 16:02 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +            modifier = modifier
아! 너무 좋은 코멘트라고 생각해

나는 이거 modifier 객체를 Modifier 를 통해서 생성해서 사용하도록 하면 recomposition 때 마다 Modifier 객체가 생성되는 것으로 들었던 것 같아서, clickable 이나 background 처럼 역할이나 배경색..? 같은걸 지정하는 로직이 아니라면 파라미터를 통해서 넘겨받도록 하면 불필요한 객체생성을 막을 수 있어서 좋다고 생각하고 이렇게 작성했었어!

근데 이런 생각은 Composable 잘 안써보고 주워들었던 얘기들을 바탕으로 작성한거긴한데.. 혹시 지혜는 어떤 경우에 파라미터로 Modifier 를 받지 않고 직접 생성해서 Modifier 를 반영하는지 알 수 있을까?

2024-06-15 16:09 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/main/MainScreen.kt
> +                NavHost(
코드 작성하면서 저거 길어지면 보기 불편하겠단 생각이 들었었는데, 그런면에서 NavHost 부분을 별도 함수로 빼는거 너무 좋은생각인 것 같아! 반영했어~ https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/1d9c8de16d7dd097439d9ac10ef6d35d5c30ff70

2024-06-16 00:31 UTC, oreocube commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +            modifier = modifier
아하 그런 이유에서라면 파일에 private 변수로 모디파이어 하나 선언해서 쓰는건 어때? 그러면 우려했던 부분도 해결되고 혹시모를 UI 이슈도 방지 가능할 것 같은뎅? 근데 이건 기억이 좀 가물가물한데 컴포저블 함수는 변경된 인자만 체크하지 않아? 모디파이어는 안바뀔테니까 괜찮지 않..나?

나는 일단 컴포저블 함수에서 가장 밖에 있는 부분에만 인자로 받은 modifier를 넣어주고 하위에 있는 애들은 그냥 Modifier 만들어서 넣어! 그리고 하위 내용물의 속성을 받아야 한다면(예를들면 TopBar 텍스트 색상 같은?) 인자로 textColor 처럼 직접적인 파라미터를 추가할 듯? 

개인적으로 TopBar를 사용하는 스크린에서 모디파이어에 어떤 속성을 지정하게 될지 모르는데 하위 컴포저블에서 공유하는건 좀 위험한 것 같아! 만약에 스크린에서 TopBar 에 그림자 속성을 주게되면 텍스트에도 그림자가 그려지지 않을까? 사실 이런건 눈에 잘보이는데 패딩같은거 넣으면 이제 디버깅 지옥이 시작되는거지

2024-06-16 03:19 UTC, sooziini commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
호옥시 두 눈의 의미는..?! 논의가
필요하다 이해가 안 간다??👀

2024-06-16 13:58 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
아 나는 저 눈 이모티콘을 코멘트 확인은 했는데, 어떻게하면 좋을지 생각/검토 중인 상태를 의미할 때 이렇게 붙여! 확인이 다 끝나면 코멘트를 추가로 달곤 해

2024-06-16 16:07 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/main/MainScreen.kt
> +                        },
오 형..! 좋은 코멘트 고마워!

생각해보니 Navigator 에서 이전 화면에 대한 route 값을 받을 수 있네..! 

우리 앱이 화면 하나에 Route 가 있고, 이에 대해 TopBarState 가 1:1 로 대응되는 특성이 보여서 Route Sealed class 안에 TopBarState 정보를 넣어두고 이를 이용해서 viewModel 에서 update 함수 하나로 관리하도록 반영해보았는데 내가 형의 코멘트를 맞게 이해하고 수정한건지 확인해줄 수 있을까?! https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/ad3ea07af0b938779faf4439176eef66a060ebcd

2024-06-16 16:23 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
> 지금 TopBar가 Main, Progress, Title 세 개가 있는데 밑에 두 개 케이스 등 더 추가되어야 할듯해!!

아! 맞아 다른 타입들도 추가되어야하는데,, 지금은 Navigation 및 TopBar 의 구조만 잡아두기 위해 작성한 것이어서..! 디자인에 맞는 적절한 TopBar 타입들은 별도의 issue 생성해서 PR 다시 올릴게! 지금 TopBarState 및 TopBar Composable 들은 샘플 코드인것만 참고해줘~!

2024-06-16 16:23 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
> 그래서 나아는 개인적으로 특정한 topbar를 여러개 생성해두는 것보다는 TopBar 컴포저블 하나 만들어서 매개변수로 iconRes, text style, text align 등 커스텀하게 만들 수 있도록 넘겨주는 것은 어떨까 싶엉 디폴트 TobBar를 두고 커스텀 하고 싶으면 매개변수로 넘기는 느낌~

아 TopBar 컴포저블 하나에 매개변수로 커스텀하게 만드는것도 너무 좋은 아이디어인데..!
전에 드로이드나이츠에서 "Compose UI 컴포넌트 설계와 테스트" 세션을 들었었는데, Component 나눌 때 과도하게 parameter 로 받아서 처리하면 Component 안에 조건문이 많이 생겨지면서 변경사항에 유연하게 대처하기 어려워질 수 있다고 하더라구..!
우리 앱 디자인 보니까 진행도표시/뒤로가기/메인화면 등 다양한 형태를 갖는 것 같아서, 변경에 유연하게 대처할 수 있는 구조로 작성하려면 여러개의 TopBar 타입을 두는게 좋을 것 같다고 생각해서 이렇게 코드를 작성한 것이었어!

혹시 우려되는 부분이 있는걸까?!

2024-06-17 03:50 UTC, sooziini commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
맞네 나도 드나 그 세션 들어서 기억난당. 다만 오빠가 말한 것처럼 다른 타입의 topbar들도 추가되어야 하는데 매번 새로운 타입의 topbar를 추가하면 중복 코드가 많아지고 조오금 비효율적이지 않나 싶어서..!

예를 들면 progress topbar는 아래 topbar에 progress bar만 추가된 형태이니까 아래 topbar를 구현해놓고 progress bar visible인지 아닌지 판단하는 값을 넘겨주면 중복 코드를 없앨 수 있을 거 같은 느낌이랄까
<img width="191" alt="image" src="https://github.com/mash-up-kr/gabbangzip-Android/assets/51108983/cddb92af-454c-4585-bfd1-cc6c3f66975e">
<img width="189" alt="image" src="https://github.com/mash-up-kr/gabbangzip-Android/assets/51108983/cf2ba8f1-d779-4eb9-b52d-5702c1f1d006">

나는 매개변수로 커스텀하게 만들긴해서 이건 진짜 취향인 거 같은데 정우 지혜 생각은 어떠신지?ㅡ?
@SEO-J17 @oreocube

2024-06-17 05:51 UTC, oreocube commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +fun TopBarMain(
나두 매개변수로 넣는 편이긴 한데 왜냐면 그다지 복잡한 걸 만들어본적이 없어 ㅎㅎ.. 
근데 프로그레스 는 진행도 값 같은거 받으려면 타입 따로 있어도 괜찮지 않을까? 아니면 아예 프로그래스를 스크린마다 넣어도 되고(?)

2024-06-18 15:14 UTC, JeonK1 commented on presentation/src/main/java/com/mashup/gabbangzip/sharedalbum/presentation/common/topbar/type/TopBarMain.kt
> +            modifier = modifier
Modifier 를 얼마나 재사용해야하나에 대한 기준이 잘 안잡힌 상태였는데 찬찬히 읽고 고민해보니
지혜가 알려준 요 기준대로 하면 딱 적당할 것 같다는 생각이 들었어! 
코멘트 고마워~ 적용했어! https://github.com/mash-up-kr/gabbangzip-Android/pull/16/commits/de226cee52fe88cd1d76c2791a7585cecebd5ad5

2024-06-19 13:11 UTC, SEO-J17 reviewed
고생했다 계원아.. 계속 질문 남겨서 먄.. 우리 이따가 토오론 해보자구.

2024-06-19 14:43 UTC, sooziini commented
논의 내용 정리

1) topbar
- progress바를 따로 빼고 topbar 컴포저블 하나로 처리하기. 매개변수로 필요한 값 전달
- topbar가 다이나믹해서 topbar 유지하지 말고 화면마다 topbar 선언하고 mainviewmodel, topbarstate 제거
2) activity 나누자 (네이밍 중요.)
- SplashActivity (os12이상? 기본 제공 splash 없애자)
- LoginActivity
- MainActivity
- GroupCreationActivity
- EventCreationActivity
- 패키지명도 변경해주면 고맙겠삼ㅎㅎ
3) 함수에 viewmodel 전달하는 방식 지양하자 람다 쓰삼

2024-06-19 15:18 UTC, JeonK1 commented
+) UI 관련 구조를 presentation 이 아니라 presentation 안의 ui 안에서 구현되도록 수정

2024-06-20 14:53 UTC, JeonK1 commented
나 이거 사실상 코드 다시 짜야해서 불필요한 commit 을 줄이는 겸 PR 다시 만들어서 올릴께!

2024-06-20 14:53 UTC, closed without merging